import argparse
import base64
import json
import queue
import re
import subprocess
import sys
import threading
import time
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

import requests
import websocket

from adspower_autofill_runner import discover, safe_label, start_main, start_observer


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")


ROOT = Path(__file__).resolve().parent


def ts() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def now_iso() -> str:
    return datetime.now().isoformat()


def b64(text_or_bytes) -> str:
    if isinstance(text_or_bytes, str):
        text_or_bytes = text_or_bytes.encode("utf-8", errors="replace")
    return base64.b64encode(text_or_bytes).decode("ascii")


def header_list(headers: dict) -> list[dict]:
    out = []
    for k, v in (headers or {}).items():
        if v is None:
            continue
        out.append({"name": str(k), "value": str(v)})
    return out


def normalize_headers_for_fetch(headers: dict) -> dict:
    """Headers captured by Fetch.requestPaused -> JS fetch headers.

    Browser-forbidden or transport-owned headers are intentionally dropped.
    The browser will add cookies/origin/sec-fetch/content-length itself.
    """
    drop = {
        "host",
        "connection",
        "content-length",
        "cookie",
        "origin",
        "referer",  # keep referrer separately is hard from JS; page normally supplies it.
        "sec-fetch-site",
        "sec-fetch-mode",
        "sec-fetch-dest",
        "sec-fetch-user",
        "accept-encoding",
    }
    cleaned = {}
    for k, v in (headers or {}).items():
        lk = k.lower()
        if lk in drop:
            continue
        # JS cannot set most Sec-* headers, but sec-ch-ua* is accepted in Chromium only when
        # generated by the browser. Let the browser regenerate them.
        if lk.startswith("sec-"):
            continue
        cleaned[k] = v
    return cleaned


def normalize_headers_for_requests(headers: dict) -> dict:
    drop = {
        "host",
        "connection",
        "content-length",
        "accept-encoding",
        "sec-fetch-site",
        "sec-fetch-mode",
        "sec-fetch-dest",
        "sec-fetch-user",
    }
    out = {}
    for k, v in (headers or {}).items():
        if k.lower() in drop:
            continue
        out[k] = v
    return out


class CreateAccountTakeover:
    def __init__(self, endpoint: str, out_path: Path, replay_mode: str, timeout_seconds: int):
        self.endpoint = endpoint.rstrip("/")
        self.out_path = out_path
        self.replay_mode = replay_mode
        self.stop_at = time.time() + max(5, timeout_seconds)
        self.ws = None
        self.next_id = 0
        self.lock = threading.RLock()
        self.pending: dict[int, dict] = {}
        self.sessions: dict[str, dict] = {}
        self.attached_targets: set[str] = set()
        self.paused: dict[str, dict] = {}
        self.done = threading.Event()
        self.result: dict | None = None
        self.main_session_id: str | None = None
        self.requests: dict[tuple[str, str], dict] = {}
        self.risk_response_count: dict[str, int] = {}
        self.fetch_armed_sessions: set[str] = set()

    def write(self, obj: dict):
        self.out_path.parent.mkdir(parents=True, exist_ok=True)
        with self.out_path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(obj, ensure_ascii=False, separators=(",", ":")) + "\n")

    def browser_ws_url(self) -> str:
        data = requests.get(self.endpoint + "/json/version", timeout=5).json()
        return data["webSocketDebuggerUrl"]

    def send(self, method: str, params: dict | None = None, session_id: str | None = None, action=None) -> int:
        with self.lock:
            self.next_id += 1
            mid = self.next_id
            msg = {"id": mid, "method": method, "params": params or {}}
            if session_id:
                msg["sessionId"] = session_id
            if action:
                self.pending[mid] = {"method": method, "session_id": session_id, "action": action}
            self.ws.send(json.dumps(msg))
            return mid

    def attach_target(self, target_info: dict):
        tid = target_info.get("targetId")
        typ = target_info.get("type") or ""
        if not tid or tid in self.attached_targets:
            return
        # Only the top-level signup page can send CreateAccount.  Avoid attaching
        # Fetch domains to hsprotect/df iframes so the captcha path stays as close
        # to the proven baseline as possible.
        if typ != "page":
            return
        self.attached_targets.add(tid)
        self.send("Target.attachToTarget", {"targetId": tid, "flatten": True}, action=("attach", target_info))

    def enable_session(self, sid: str, target_info: dict):
        self.sessions[sid] = target_info or {}
        print(
            f"[Takeover] attach session={sid} type={target_info.get('type')} "
            f"title={target_info.get('title')} url={target_info.get('url')}",
            flush=True,
        )
        self.send("Runtime.enable", {}, session_id=sid)
        self.send("Network.enable", {}, session_id=sid)
        # Do NOT enable Fetch immediately.  Even with a narrow URL pattern it can
        # perturb a sensitive challenge run.  We arm it only after the post-captcha
        # risk/verify response headers arrive, immediately before CreateAccount.

    def handle_response(self, msg: dict):
        mid = msg.get("id")
        item = self.pending.pop(mid, None)
        if not item:
            return
        kind, payload = item.get("action")
        sid = item.get("session_id")
        if kind == "attach":
            new_sid = ((msg.get("result") or {}).get("sessionId"))
            if new_sid:
                self.enable_session(new_sid, payload or {})
        elif kind == "getTargets":
            for t in ((msg.get("result") or {}).get("targetInfos") or []):
                self.attach_target(t)
        elif kind == "runtime_fetch":
            self.on_runtime_fetch_result(sid, payload, msg)
        elif kind == "cookies_then_python":
            self.on_python_replay(payload, msg)

    def handle_event(self, msg: dict):
        method = msg.get("method") or ""
        params = msg.get("params") or {}
        sid = msg.get("sessionId")
        if method == "Target.targetCreated":
            self.attach_target(params.get("targetInfo") or {})
            return
        if method == "Target.attachedToTarget":
            new_sid = params.get("sessionId")
            ti = params.get("targetInfo") or {}
            tid = ti.get("targetId")
            if tid:
                self.attached_targets.add(tid)
            if new_sid:
                self.enable_session(new_sid, ti)
            return
        if method == "Network.requestWillBeSent" and sid:
            self.on_network_request(sid, params)
            return
        if method == "Network.responseReceived" and sid:
            self.on_network_response(sid, params)
            return
        if method == "Fetch.requestPaused" and sid:
            self.on_request_paused(sid, params)

    def arm_fetch(self, sid: str, why: str):
        if sid in self.fetch_armed_sessions:
            return
        self.fetch_armed_sessions.add(sid)
        print(f"[Takeover] arming Fetch on session={sid} reason={why}", flush=True)
        self.write({"ts": now_iso(), "event": "fetch_armed", "session_id": sid, "reason": why})
        self.send(
            "Fetch.enable",
            {
                "patterns": [
                    {
                        "urlPattern": "*://signup.live.com/API/CreateAccount*",
                        "requestStage": "Request",
                    }
                ]
            },
            session_id=sid,
        )

    def on_network_request(self, sid: str, params: dict):
        req = params.get("request") or {}
        rid = params.get("requestId")
        url = req.get("url") or ""
        post_data = req.get("postData") or ""
        if rid:
            self.requests[(sid, rid)] = {
                "method": req.get("method"),
                "url": url,
            }
        if (
            "login.microsoftonline.com" in url
            and "/api/v1.0/risk/verify" in url
            and not self.done.is_set()
            and "challengeSolution" in post_data
        ):
            # This is the post-captcha risk/verify request.  In successful traces
            # CreateAccount is scheduled shortly after this request, often before
            # the continue response body is available.  Arm Fetch here: late enough
            # not to perturb hsprotect, early enough to catch CreateAccount.
            self.write(
                {
                    "ts": now_iso(),
                    "event": "post_captcha_risk_request",
                    "session_id": sid,
                    "request_id": rid,
                    "post_len": len(post_data),
                }
            )
            self.arm_fetch(sid, "post_captcha_risk_request")

    def on_network_response(self, sid: str, params: dict):
        resp = params.get("response") or {}
        url = resp.get("url") or ""
        if "login.microsoftonline.com" in url and "/api/v1.0/risk/verify" in url:
            n = self.risk_response_count.get(sid, 0) + 1
            self.risk_response_count[sid] = n
            self.write(
                {
                    "ts": now_iso(),
                    "event": "risk_verify_response_headers",
                    "session_id": sid,
                    "count": n,
                    "status": resp.get("status"),
                    "url": url,
                }
            )
            # Do not arm here.  Duplicate page sessions make response counts
            # ambiguous; arming on the initial challenge response caused a
            # measurable re-challenge drift.  We arm only on post-captcha
            # risk/verify request bodies in on_network_request().

    def on_request_paused(self, sid: str, params: dict):
        req = params.get("request") or {}
        url = req.get("url") or ""
        if "signup.live.com/API/CreateAccount" not in url or self.done.is_set():
            self.send("Fetch.continueRequest", {"requestId": params.get("requestId")}, session_id=sid)
            return

        request_id = params.get("requestId")
        rec = {
            "ts": now_iso(),
            "event": "paused_create_account",
            "session_id": sid,
            "request_id": request_id,
            "method": req.get("method"),
            "url": url,
            "headers": req.get("headers") or {},
            "post_data": req.get("postData") or "",
            "target": self.sessions.get(sid) or {},
            "replay_mode": self.replay_mode,
        }
        self.paused[request_id] = rec
        self.main_session_id = sid
        self.write(rec)
        print(f"[Takeover] paused CreateAccount; mode={self.replay_mode}", flush=True)

        if self.replay_mode == "page-fetch":
            self.start_page_fetch(sid, rec)
        elif self.replay_mode == "python-requests":
            # Best-effort cookie harvest. If it fails, on_python_replay still falls back to headers.
            self.send("Network.getAllCookies", {}, session_id=sid, action=("cookies_then_python", rec))
        else:
            raise ValueError(f"unsupported replay_mode={self.replay_mode}")

    def start_page_fetch(self, sid: str, rec: dict):
        # Disable Fetch around injected fetch, otherwise our injected request pauses itself.
        self.send("Fetch.disable", {}, session_id=sid)
        js_headers = normalize_headers_for_fetch(rec.get("headers") or {})
        expression = f"""
(async () => {{
  const url = {json.dumps(rec["url"])};
  const body = {json.dumps(rec.get("post_data") or "")};
  const headers = {json.dumps(js_headers)};
  const started = Date.now();
  try {{
    const r = await fetch(url, {{
      method: "POST",
      headers,
      body,
      credentials: "include",
      cache: "no-store",
      mode: "cors"
    }});
    const text = await r.text();
    return {{
      ok: r.ok,
      status: r.status,
      statusText: r.statusText,
      elapsedMs: Date.now() - started,
      headers: Array.from(r.headers.entries()),
      body: text
    }};
  }} catch (e) {{
    return {{
      ok: false,
      status: 0,
      statusText: String(e && (e.stack || e.message || e)),
      elapsedMs: Date.now() - started,
      headers: [],
      body: ""
    }};
  }}
}})()
"""
        self.send(
            "Runtime.evaluate",
            {"expression": expression, "awaitPromise": True, "returnByValue": True},
            session_id=sid,
            action=("runtime_fetch", rec),
        )

    def on_runtime_fetch_result(self, sid: str, rec: dict, msg: dict):
        val = (((msg.get("result") or {}).get("result") or {}).get("value")) or {}
        body = val.get("body") or ""
        status = int(val.get("status") or 599)
        response_headers = {}
        for pair in val.get("headers") or []:
            if isinstance(pair, list) and len(pair) == 2:
                response_headers[str(pair[0])] = str(pair[1])
        if "content-type" not in {k.lower(): v for k, v in response_headers.items()}:
            response_headers["content-type"] = "application/json; charset=utf-8"
        out = {
            "ts": now_iso(),
            "event": "replay_result",
            "mode": "page-fetch",
            "status": status,
            "ok": bool(val.get("ok")),
            "elapsedMs": val.get("elapsedMs"),
            "statusText": val.get("statusText"),
            "body": body[:4000],
            "signinName": self.extract_signin(body),
        }
        self.result = out
        self.write(out)
        print(
            f"[Takeover] page-fetch status={status} ok={out['ok']} signin={out.get('signinName') or '-'}",
            flush=True,
        )
        self.fulfill_original(sid, rec, status, response_headers, body)

    def on_python_replay(self, rec: dict, msg: dict):
        cookies = []
        if "result" in msg:
            cookies = ((msg.get("result") or {}).get("cookies") or [])
        headers = normalize_headers_for_requests(rec.get("headers") or {})
        sess = requests.Session()
        host = urlparse(rec["url"]).hostname or ""
        for c in cookies:
            domain = c.get("domain") or ""
            if host.endswith(domain.lstrip(".")):
                sess.cookies.set(c.get("name"), c.get("value"), domain=domain, path=c.get("path") or "/")
        try:
            started = time.time()
            resp = sess.post(rec["url"], data=rec.get("post_data") or "", headers=headers, timeout=45)
            elapsed = int((time.time() - started) * 1000)
            body = resp.text
            status = resp.status_code
            response_headers = dict(resp.headers)
            out = {
                "ts": now_iso(),
                "event": "replay_result",
                "mode": "python-requests",
                "status": status,
                "ok": 200 <= status < 300,
                "elapsedMs": elapsed,
                "cookie_count": len(sess.cookies),
                "body": body[:4000],
                "signinName": self.extract_signin(body),
            }
        except Exception as exc:
            status, body, response_headers = 599, json.dumps({"error": repr(exc)}, ensure_ascii=False), {
                "content-type": "application/json; charset=utf-8"
            }
            out = {
                "ts": now_iso(),
                "event": "replay_result",
                "mode": "python-requests",
                "status": status,
                "ok": False,
                "error": repr(exc),
                "body": body,
            }
        self.result = out
        self.write(out)
        print(
            f"[Takeover] python-requests status={status} ok={out.get('ok')} signin={out.get('signinName') or '-'}",
            flush=True,
        )
        self.fulfill_original(rec["session_id"], rec, status, response_headers, body)

    @staticmethod
    def extract_signin(body: str) -> str:
        try:
            parsed = json.loads(body or "{}")
            return parsed.get("signinName") or ""
        except Exception:
            m = re.search(r'"signinName"\s*:\s*"([^"]+)"', body or "")
            return m.group(1) if m else ""

    def fulfill_original(self, sid: str, rec: dict, status: int, response_headers: dict, body: str):
        request_id = rec.get("request_id")
        # Keep browser/main.py consistent with the replay result and do not send the original request.
        params = {
            "requestId": request_id,
            "responseCode": int(status or 599),
            "responseHeaders": header_list(response_headers),
            "body": b64(body or ""),
        }
        self.send("Fetch.fulfillRequest", params, session_id=sid)
        self.done.set()

    def run(self):
        print(f"[Takeover] log={self.out_path.resolve()}", flush=True)
        self.ws = websocket.create_connection(self.browser_ws_url(), timeout=5, suppress_origin=True)
        self.ws.settimeout(1.0)
        self.send("Target.setDiscoverTargets", {"discover": True})
        self.send(
            "Target.setAutoAttach",
            {"autoAttach": True, "waitForDebuggerOnStart": False, "flatten": True},
        )
        self.send("Target.getTargets", {}, action=("getTargets", None))
        next_poll = time.time() + 2
        while time.time() < self.stop_at:
            if time.time() >= next_poll:
                self.send("Target.getTargets", {}, action=("getTargets", None))
                next_poll = time.time() + 2
            try:
                msg = json.loads(self.ws.recv())
            except websocket.WebSocketTimeoutException:
                if self.done.is_set():
                    break
                continue
            except Exception as exc:
                print(f"[Takeover] recv end: {exc!r}", flush=True)
                break
            if "id" in msg:
                self.handle_response(msg)
            else:
                self.handle_event(msg)
        print("[Takeover] done", flush=True)


def pump_stdout(name: str, proc: subprocess.Popen, out_queue: queue.Queue):
    try:
        assert proc.stdout is not None
        for line in proc.stdout:
            out_queue.put((name, line))
    finally:
        out_queue.put((name, None))


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Pause browser CreateAccount and replay it from a protocol-controlled path."
    )
    ap.add_argument("--user-id", required=True)
    ap.add_argument("--label", default=None)
    ap.add_argument("--profile-dir", default=None)
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--config", default="config.ctf.risk_probe.ads_original_fill_hold8500_10500.json")
    ap.add_argument("--mode", choices=["auto-hold", "manual-captcha"], default="auto-hold")
    ap.add_argument("--replay-mode", choices=["page-fetch", "python-requests"], default="page-fetch")
    ap.add_argument("--timeout-seconds", type=int, default=600)
    ap.add_argument("--success-grace-seconds", type=float, default=12.0)
    ap.add_argument("--email", default=None)
    ap.add_argument("--password", default=None)
    ap.add_argument("--out-dir", default="Results/network")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    label = safe_label(args.label or f"{args.user_id}_{args.replay_mode}")
    info = discover(args.user_id, args.host, args.profile_dir, 5.0)
    print(json.dumps(info, ensure_ascii=False, indent=2), flush=True)

    stamp = ts()
    cdp_endpoint = info["cdp_endpoint"]
    observer_log = Path(args.out_dir) / f"takeover_{label}_{stamp}.browser_cdp.jsonl"
    takeover_log = Path("Results/protocol_runtime") / f"takeover_{label}_{stamp}.takeover.jsonl"
    meta_path = Path("Results/protocol_runtime") / f"takeover_{label}_{stamp}.meta.json"
    meta = {
        "label": label,
        "user_id": args.user_id,
        "cdp_endpoint": cdp_endpoint,
        "browser": info.get("browser"),
        "config": args.config,
        "mode": args.mode,
        "replay_mode": args.replay_mode,
        "observer_log": str(observer_log),
        "takeover_log": str(takeover_log),
        "meta": str(meta_path),
    }
    if args.dry_run:
        print(json.dumps(meta, ensure_ascii=False, indent=2), flush=True)
        return 0

    takeover = CreateAccountTakeover(cdp_endpoint, takeover_log, args.replay_mode, args.timeout_seconds)
    t = threading.Thread(target=takeover.run, daemon=True)
    t.start()
    time.sleep(1.0)

    observer = start_observer(cdp_endpoint, observer_log, args.timeout_seconds)
    main_proc = start_main(
        endpoint=cdp_endpoint,
        config=args.config,
        mode=args.mode,
        max_tasks=1,
        concurrent=1,
        email=args.email,
        password=args.password,
        manual_wait_seconds=args.timeout_seconds,
        manual_post_wait_seconds=10,
        skip_preflight=True,
    )
    q: queue.Queue = queue.Queue()
    threading.Thread(target=pump_stdout, args=("observer", observer, q), daemon=True).start()
    threading.Thread(target=pump_stdout, args=("main", main_proc, q), daemon=True).start()

    started = time.time()
    grace_started = None
    main_done = False
    try:
        while time.time() - started < args.timeout_seconds:
            try:
                name, line = q.get(timeout=0.3)
            except queue.Empty:
                name, line = "", ""
            if line is None:
                if name == "main":
                    main_done = True
                    break
                continue
            if line:
                print(("[Observer] " if name == "observer" else "[Main] ") + line, end="", flush=True)
            if takeover.done.is_set() and grace_started is None:
                grace_started = time.time()
                print(
                    f"[Takeover] replay finished; keeping main alive {args.success_grace_seconds:.1f}s",
                    flush=True,
                )
            if grace_started and time.time() - grace_started >= args.success_grace_seconds:
                break
    finally:
        if main_proc.poll() is None:
            main_proc.terminate()
            try:
                main_proc.wait(timeout=8)
            except subprocess.TimeoutExpired:
                main_proc.kill()
        if observer.poll() is None:
            observer.terminate()
            try:
                observer.wait(timeout=5)
            except subprocess.TimeoutExpired:
                observer.kill()

    meta.update(
        {
            "finished_at": now_iso(),
            "main_exit": main_proc.poll(),
            "observer_exit": observer.poll(),
            "takeover_done": takeover.done.is_set(),
            "takeover_result": takeover.result,
        }
    )
    meta_path.parent.mkdir(parents=True, exist_ok=True)
    meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[Takeover] meta={meta_path}", flush=True)
    if takeover.result:
        print(json.dumps(takeover.result, ensure_ascii=False, indent=2), flush=True)
        return 0 if takeover.result.get("signinName") else 1
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
